// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bmfbiswkrleuanyoplfh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJtZmJpc3drcmxldWFueW9wbGZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ5Njc5MDYsImV4cCI6MjA5MDU0MzkwNn0.uHtVJacFohcmusSJW2QD0kFXW64Gqt6ZvQHj62ecsu8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});