// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://paxtvlbddpemjlnftjlq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBheHR2bGJkZHBlbWpsbmZ0amxxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM5NTQ0MzEsImV4cCI6MjA5OTUzMDQzMX0.7BYs5TuvBhgCeUdJR48GrUIuqgwtnds60anSneqMlbo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
